baseURL = "/"
languageCode = "en-us"
title = "POLIW.AT"
publishDir = "docs"


theme = "sublime-hugo-theme"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-105678561-1"
paginate = 100

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Michael Betts"
	description = "open source thoughts for emotional people"
	copyright = "Omari, SC-LLC"
	avatar = "/images/mike1.png"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Future"
	older = "Past"

	pageNotFoundTitle = "What is lost, will be found."
	pageNotFoundSubtitle = "But it won't be what you lost."

[params.offcanvas]
	# Menu items
	title = "This site is"
	bio= "1 - an audio journal <br><br>2 - my brain dumping grounds <br><br> 3 - my safe space <br><br> 4 -  "
	subscribe = "New Audio every day, so help me God"
	followme = "nope"

	# Enable Google search
	search_enabled = true
	search = "this doesn't work"
