baseURL = "http://example.org/"
languageCode = "en-us"
title = "POLIWAT."

theme = "sublime-hugo-theme"

# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 50

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Michael Betts"
	description = "open source thoughts for emotional people"
	copyright = "Omari LLC"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Future"
	older = "Past"

	pageNotFoundTitle = "What is lost, will be found."
	pageNotFoundSubtitle = "But it won't be what you lost."

[params.offcanvas]
	# Menu items
	title = "Omari Production"
	bio = "Walmarts Everywhere"
	bio2 = "Santa Cruz, CA"
	subscribe = "Help"
	followme = "Contact"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "michael"
		url = "michaelflops@gmail.com"
